# JVM and Kotlin settings
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.20.101-hotspot
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2

# Android settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Compose Multiplatform
org.jetbrains.compose.experimental.uikit.enabled=true
