const url = 'https://kjoykvxrnyykdnzektoj.supabase.co/rest/v1/offerings';
const anonKey = 'sb_publishable_PNb4_Epkaqv-J1KdC0x7dQ_-vxdAt-d';

async function insertTestLabel() {
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'apikey': anonKey,
        'Authorization': `Bearer ${anonKey}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=representation'
      },
      body: JSON.stringify({
        // DO NOT send id, it's a UUID generated by Supabase
        title_gu: 'ટેસ્ટિંગ લેબલ - ડેટાબેઝ જોડાયેલ છે',
        title_en: 'TESTING LABEL - DB Connected!',
        description_gu: 'આ માત્ર ડેટાબેઝ કનેક્શન તપાસવા માટે છે.',
        description_en: 'This is just to verify the database connection from both Web and Mobile apps.',
        amount: 101,
        quantity: 1,
        status: 'ACTIVE',
        location_gu: 'ટેસ્ટ લોકેશન',
        location_en: 'Test Location'
      })
    });
    
    if (response.ok) {
      console.log('Successfully inserted testing label!');
      const data = await response.json();
      console.log(data);
    } else {
      console.error('Failed:', response.status, await response.text());
    }
  } catch (err) {
    console.error('Fetch error:', err.message);
  }
}

insertTestLabel();
